### ISSUE TITLE
Panics on Linux

### ISSUE THREAD

**Issue by aprzn123** [a2aaron/nyasynth#3]
I'm trying to install this plugin on my Fedora Linux machine, and I am getting an error when trying to either run the standalone version or load either the vst3 or clap in Zrythm. Any idea what could be going on here?

Here is the error when running the standalone version:
```
21:14:26 [INFO] Loading jack from libjack.so.0.
21:14:26 [INFO] Using the JACK backend
Could not get the local time offset, defaulting to UTC
21:14:26 [INFO] Initalizing VST...
21:14:26 [ERROR] thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported(UnsupportedError { format: Unknown, kind: Format(Unknown) })': src/ui.rs:195
   0: nih_plug::util::permit_alloc
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panicking.rs:64:14
   6: core::result::unwrap_failed
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1790:5
   7: nyasynth::ui::load_image_from_memory
   8: nyasynth::ui::get_editor::{{closure}}
   9: baseview::x11::window::Window::window_thread
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys/unix/thread.rs:108:17
  13: start_thread
  14: __GI___clone3

21:14:26 [ERROR] thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/eae4033/src/x11/window.rs:143
   0: nih_plug::util::permit_alloc
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panicking.rs:64:14
   6: core::result::unwrap_failed
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1790:5
   7: <nih_plug_egui::editor::EguiEditor<T> as nih_plug::editor::Editor>::spawn
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys/unix/thread.rs:108:17
  11: start_thread
  12: __GI___clone3

21:14:26 [ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/7001c25/src/x11/window.rs:181
   0: nih_plug::util::permit_alloc
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panicking.rs:64:14
   6: core::result::unwrap_failed
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1790:5
   7: nih_plug::wrapper::standalone::wrapper::Wrapper<P,B>::run
   8: nih_plug::wrapper::standalone::nih_export_standalone
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: main
  11: __libc_start_call_main
  12: __libc_start_main@GLIBC_2.2.5
  13: _start
```

I tried running a debug build in standalone too, in case that helped anything. Here's the log from that:

```
21:30:58 [INFO] Loading jack from libjack.so.0.
21:30:58 [INFO] Using the JACK backend
Could not get the local time offset, defaulting to UTC
21:30:58 [INFO] Initalizing VST...
21:30:58 [DEBUG] (1) nih_plug::wrapper::standalone::context: Debug assertion failed: TODO: WrapperInitContext::set_latency_samples()
21:30:59 [ERROR] thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported(UnsupportedError { format: Unknown, kind: Format(Unknown) })': src/ui.rs:195
   0: nih_plug::wrapper::util::log_panics::{{closure}}::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/util.rs:128:29
   1: nih_plug::util::permit_alloc
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/util.rs:25:5
   2: nih_plug::wrapper::util::log_panics::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/util.rs:125:9
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:692:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:579:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:137:18
   6: rust_begin_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:575:5
   7: core::panicking::panic_fmt
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panicking.rs:64:14
   8: core::result::unwrap_failed
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1790:5
   9: core::result::Result<T,E>::unwrap
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1112:23
  10: nyasynth::ui::load_image_from_memory
             at src/ui.rs:195:17
  11: nyasynth::ui::get_editor::{{closure}}::{{closure}}
             at src/ui.rs:219:29
  12: nyasynth::ui::get_editor::{{closure}}::{{closure}}
             at src/ui.rs:239:29
  13: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/adapters/map.rs:84:28
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/adapters/enumerate.rs:106:27
  15: core::iter::traits::iterator::Iterator::fold
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/traits/iterator.rs:2438:21
  16: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/adapters/enumerate.rs:112:9
  17: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/adapters/map.rs:124:9
  18: core::iter::traits::iterator::Iterator::for_each
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/traits/iterator.rs:837:9
  19: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/vec/mod.rs:2856:17
  20: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/vec/spec_extend.rs:26:9
  21: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/vec/spec_from_iter.rs:33:9
  23: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/vec/mod.rs:2724:9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/iter/traits/iterator.rs:1860:9
  25: nyasynth::ui::get_editor::{{closure}}
             at src/ui.rs:225:26
  26: <nih_plug_egui::editor::EguiEditor<T> as nih_plug::editor::Editor>::spawn::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/nih_plug_egui/src/editor.rs:75:44
  27: egui_baseview::window::EguiWindow<State,U>::new
             at /home/aprzn/.cargo/git/checkouts/egui-baseview-86e23f13b9c000a6/46e21cc/src/window.rs:143:9
  28: egui_baseview::window::EguiWindow<State,U>::open_parented::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/egui-baseview-86e23f13b9c000a6/46e21cc/src/window.rs:205:17
  29: baseview::x11::window::Window::window_thread
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/eae4033/src/x11/window.rs:354:27
  30: baseview::x11::window::Window::open_parented::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/eae4033/src/x11/window.rs:140:13
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:121:18
  32: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/thread/mod.rs:558:17
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panic/unwind_safe.rs:271:9
  34: std::panicking::try::do_call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:483:40
  35: __rust_try
  36: std::panicking::try
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:447:19
  37: std::panic::catch_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panic.rs:140:14
  38: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/thread/mod.rs:557:30
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/ops/function.rs:250:5
  40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys/unix/thread.rs:108:17
  41: start_thread
  42: __GI___clone3

21:30:59 [ERROR] thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/eae4033/src/x11/window.rs:143
   0: nih_plug::wrapper::util::log_panics::{{closure}}::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/util.rs:128:29
   1: nih_plug::util::permit_alloc
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/util.rs:25:5
   2: nih_plug::wrapper::util::log_panics::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/util.rs:125:9
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:692:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:579:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:137:18
   6: rust_begin_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:575:5
   7: core::panicking::panic_fmt
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panicking.rs:64:14
   8: core::result::unwrap_failed
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1790:5
   9: core::result::Result<T,E>::unwrap
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1112:23
  10: baseview::x11::window::Window::open_parented
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/eae4033/src/x11/window.rs:143:33
  11: baseview::window::Window::open_parented
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/eae4033/src/window.rs:73:29
  12: egui_baseview::window::EguiWindow<State,U>::open_parented
             at /home/aprzn/.cargo/git/checkouts/egui-baseview-86e23f13b9c000a6/46e21cc/src/window.rs:201:9
  13: <nih_plug_egui::editor::EguiEditor<T> as nih_plug::editor::Editor>::spawn
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/nih_plug_egui/src/editor.rs:46:22
  14: nih_plug::wrapper::standalone::wrapper::Wrapper<P,B>::run::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/standalone/wrapper.rs:349:45
  15: baseview::x11::window::Window::window_thread
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/7001c25/src/x11/window.rs:354:27
  16: baseview::x11::window::Window::open_blocking::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/7001c25/src/x11/window.rs:178:13
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:121:18
  18: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/thread/mod.rs:558:17
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:483:40
  21: __rust_try
  22: std::panicking::try
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:447:19
  23: std::panic::catch_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panic.rs:140:14
  24: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/thread/mod.rs:557:30
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/ops/function.rs:250:5
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys/unix/thread.rs:108:17
  27: start_thread
  28: __GI___clone3

21:30:59 [ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError': /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/7001c25/src/x11/window.rs:181
   0: nih_plug::wrapper::util::log_panics::{{closure}}::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/util.rs:128:29
   1: nih_plug::util::permit_alloc
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/util.rs:25:5
   2: nih_plug::wrapper::util::log_panics::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/util.rs:125:9
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:692:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:579:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:137:18
   6: rust_begin_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:575:5
   7: core::panicking::panic_fmt
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/panicking.rs:64:14
   8: core::result::unwrap_failed
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1790:5
   9: core::result::Result<T,E>::unwrap
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:1112:23
  10: baseview::x11::window::Window::open_blocking
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/7001c25/src/x11/window.rs:181:17
  11: baseview::window::Window::open_blocking
             at /home/aprzn/.cargo/git/checkouts/baseview-9d6c750431f4479e/7001c25/src/window.rs:104:9
  12: nih_plug::wrapper::standalone::wrapper::Wrapper<P,B>::run
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/standalone/wrapper.rs:334:17
  13: nih_plug::wrapper::standalone::run_wrapper
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/standalone.rs:188:11
  14: nih_plug::wrapper::standalone::nih_export_standalone_with_args::{{closure}}
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/standalone.rs:78:17
  15: core::result::Result<T,E>::map
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/result.rs:774:25
  16: nih_plug::wrapper::standalone::nih_export_standalone_with_args
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/standalone.rs:76:26
  17: nih_plug::wrapper::standalone::nih_export_standalone
             at /home/aprzn/.cargo/git/checkouts/nih-plug-c1b5c6efaf43945f/2ecc194/src/wrapper/standalone.rs:53:5
  18: standalone::main
             at src/bin/standalone.rs:4:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/ops/function.rs:250:5
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/sys_common/backtrace.rs:121:18
  21: std::rt::lang_start::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/rt.rs:166:18
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/rt.rs:148:20
  23: std::rt::lang_start
             at /rustc/9a7cc6c32f1a690f86827e4724bcda85e506ef35/library/std/src/rt.rs:165:17
  24: main
  25: __libc_start_call_main
  26: __libc_start_main@GLIBC_2.2.5
  27: _start
```

**Comment by a2aaron** [comment]
It seems like image loading is failing for some reason. Maybe it's unable to guess the image format? I've pushed a new commit that attempts to avoid crashing and also just tells `image` that I'm loading PNG files instead of having it guess the format. Can you try running that and seeing if that fixes the crashing?

**Comment by aprzn123** [comment]
It runs with the example image, showing this error for each image:
`Decoding(DecodingError { format: Exact(Png), underlying: Some(Format(FormatError { inner: InvalidSignature })) })`.
It does work now, although admittedly it's a bit hard to use without a GUI, lol

**Comment by a2aaron** [comment]
Huh, bizarre. I wonder if `image` behaves very different on Fedora Linux. I will try replicating this bug. Can you provide me your exact rust version (run `cargo --version`) and what version of Fedora Linux you're on? Also, if you can attach the compiled debug binary I would also appreciate that.

**Comment by a2aaron** [comment]
Okay, I think I might've figured out the issue: I was mistakenly committing the assets folder as git LFS files, which means that anyone who doesn't have git LFS on their system won't be able to download the images and instead downloads useless text-placeholder files. I've disabled git LFS for this repo. Can you try pulling and seeing if that fixes the issue?

**Comment by aprzn123** [comment]
That did fix it, thanks so much!
